library(lubridate)
library(tidyverse)
library(dplyr)
library(readr)
library(modelr)
library(tictoc)
data<-read_csv('6green_samp_select4.csv')
dat_imp<-data%>%select(-month,-addn_chg,-pu_lon,-pu_lat,-do_lon,-do_lat)
dat_imp<-dat_imp%>%mutate(dow_drop=wday(do_time),dow_pick=wday(pu_time))
dat_imp<-dat_imp%>%mutate(day_type_drop=ifelse(dow_drop %in% 2:6,1,0),
day_type_pick=ifelse(dow_pick %in% 2:6,1,0))
dat_imp$shift<-as.factor(dat_imp$shift)
dat_imp$day_type_drop<-as.factor(dat_imp$day_type_drop)
dat_imp$day_type_pick<-as.factor(dat_imp$day_type_pick)
part<-resample_partition(dat_imp,p=c(train=0.7,test=0.3))
train_dat<-as.tibble(part$train)
train_dat<-train_dat%>%filter(between(rate,2,20),between(fare_amount,0,50))
tic('model time')
fit<-lm(fare_amount~trip_distance+day_type_drop*shift,data=train_dat)
toc()
dat<-train_dat%>%mutate(preds=fit$fitted.values)
dat<-dat[,c('preds','pulocationid','dolocationid','fare_amount')]
#plot of fit on training data

ggplot(train_dat)+geom_point(mapping=aes(x=trip_distance,y=fare_amount))+geom_line(mapping = aes(x=trip_distance,y=fit$fitted.values))
pred<-add_predictions(part$test,fit)
test<-as.tibble(part$test)
predvact<-data.frame(pred$pred,test$fare_amount,test$pulocationid,test$dolocationid,test$trip_distance)
print(predvact)
rmse(fit,part$test)